/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether setup is needed and whether the caller is authenticated. */
        get: operations["getAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap the first admin user (one-shot). */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with username + password. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (admin). */
        get: operations["listUsers"];
        put?: never;
        /** Provision a user (admin). */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user (admin). */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Merged model list across all configured upstreams. */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upstreams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List redacted LLM upstream health snapshots (admin). */
        get: operations["listUpstreamHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the redacted operational readiness snapshot (admin). */
        get: operations["getAdminReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's chats, paginated. */
        get: operations["listChats"];
        put?: never;
        /**
         * Create a chat and stream the first assistant turn (SSE).
         * @description Streams Anthropic-style SSE. The new chat id is carried in the message_start event's stream_id. Advisory chat_status events report connecting, waiting_first_token, streaming, running_tool, or retrying; clients must treat them as ephemeral progress metadata rather than durable assistant content. If a real stream stops after useful output, GET /chats/{chatId}/messages returns that assistant checkpoint with incomplete=true; it is not included in later model context.
         */
        post: operations["createChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/empty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get the caller's reusable "empty chat" (no messages yet), creating one if none exists.
         * @description At most one empty chat is kept per user: repeated calls before any message is sent all resolve to the SAME chat id, so a client's "New chat" action never piles up unused rows. Once the chat's first message is sent (POST /chats/{chatId}), it stops being empty and a later call creates/returns a different chat.
         */
        post: operations["getOrCreateEmptyChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a chat's metadata (settings, model, title) — no messages.
         * @description Returns chat metadata only. Fetch messages via GET /api/v1/chats/{chatId}/messages.
         */
        get: operations["getChat"];
        put?: never;
        /**
         * Continue a chat and stream the next assistant turn (SSE).
         * @description Streams Anthropic-style SSE plus advisory chat_status progress events. A status is emitted only after its corresponding provider or tool lifecycle transition; it carries no prompt, tool, or provider payload.
         */
        post: operations["continueChat"];
        /** Soft-delete one caller-owned chat. */
        delete: operations["deleteChat"];
        options?: never;
        head?: never;
        /** Rename a chat. */
        patch: operations["renameChat"];
        trace?: never;
    };
    "/chats/{chatId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a chat's messages, oldest-first, paginated. */
        get: operations["listChatMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a chat's model-generation settings.
         * @description Full replacement of the chat's settings object: a field omitted from the body clears that setting (back to the provider default; history returns to its 100000-token default).
         */
        patch: operations["updateChatSettings"];
        trace?: never;
    };
    "/chats/{chatId}/context-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview the exact context selected for an unsent chat message. */
        post: operations["previewChatContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/mcp-servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the MCP servers with each one's per-chat enablement + status.
         * @description The MCP servers as this chat sees them: identity, live global connection status, and whether each is enabled for this chat. Ownership-checked, so a chat's owner sees it without admin access.
         */
        get: operations["listChatMCPServers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/mcp-servers/{serverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Enable or disable one MCP server for this chat. */
        patch: operations["updateChatMCPServer"];
        trace?: never;
    };
    "/chats/{chatId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Archive one caller-owned chat. */
        put: operations["archiveChat"];
        post?: never;
        /** Restore one caller-owned chat from the archive. */
        delete: operations["unarchiveChat"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Pin one caller-owned chat. */
        put: operations["pinChat"];
        post?: never;
        /** Remove a caller-owned chat pin. */
        delete: operations["unpinChat"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign one caller-owned chat to a caller-owned project. */
        put: operations["assignChatProject"];
        post?: never;
        /** Remove a caller-owned chat's project assignment. */
        delete: operations["clearChatProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's named chat projects. */
        get: operations["listProjects"];
        put?: never;
        /** Create a named chat project. */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a project and unassign its chats. */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Rename one caller-owned project. */
        patch: operations["renameProject"];
        trace?: never;
    };
    "/mcp/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured MCP servers (admin). */
        get: operations["listMCPServers"];
        put?: never;
        /** Add an MCP server (admin). */
        post: operations["createMCPServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/servers/{serverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an MCP server (admin). */
        delete: operations["deleteMCPServer"];
        options?: never;
        head?: never;
        /** Edit an MCP server and reconnect (admin). */
        patch: operations["updateMCPServer"];
        trace?: never;
    };
    "/mcp/servers/{serverId}/reconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconnect an MCP server in the background (admin). */
        post: operations["reconnectMCPServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/servers/{serverId}/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a connected MCP server's tools (admin). */
        get: operations["listMCPServerTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import MCP servers from a Claude-style .mcp.json (admin). */
        post: operations["importMCP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Health: {
            status: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            isAdmin: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        AuthStatus: {
            /** @description True when no users exist yet (first-run bootstrap). */
            needsSetup: boolean;
            authenticated: boolean;
            user?: components["schemas"]["User"];
        };
        Credentials: {
            username: string;
            password: string;
        };
        CreateUserRequest: {
            username: string;
            password: string;
            isAdmin?: boolean;
        };
        /** @description A model currently advertised by a configured upstream. Capability and limit fields are optional instance metadata; omitted fields are unknown, not false or zero. */
        Model: {
            id: string;
            upstream: string;
            /** @description A friendly instance-local model name for the picker. */
            alias?: string;
            contextWindow?: number;
            maxOutputTokens?: number;
            supportsTools?: boolean;
            supportsReasoning?: boolean;
            supportsVision?: boolean;
            supportsFiles?: boolean;
            /**
             * Format: int64
             * @description Instance-configured expected time to first token, in milliseconds.
             */
            expectedFirstTokenLatencyMs?: number;
            inputPricePerMillionTokens?: components["schemas"]["TokenPrice"];
            outputPricePerMillionTokens?: components["schemas"]["TokenPrice"];
            /**
             * @description The model was advertised by its upstream during startup discovery.
             * @enum {string}
             */
            availability: "available";
            /** @description Whether this is the instance's configured default model. */
            default: boolean;
        };
        /** @description Price for one million tokens. Amount is a decimal string in the currency's smallest unit, avoiding floating-point loss in clients. */
        TokenPrice: {
            amount: string;
            currency: string;
        };
        /** @description A redacted runtime-health snapshot for one configured LLM upstream. Failure details are stable classes only; provider response text, requests, and credentials are never exposed here. */
        UpstreamHealth: {
            upstream: string;
            /** @enum {string} */
            state: "unknown" | "healthy" | "degraded";
            lastOperation?: string;
            /** Format: int64 */
            lastLatencyMs?: number;
            /** Format: date-time */
            lastSuccessAt?: string | null;
            /** Format: date-time */
            lastFailureAt?: string | null;
            lastFailureClass?: string;
            consecutiveFailures: number;
        };
        /** @description The status of an operator-written backup completion marker. A current marker proves only that the backup command completed; it is not an archive-content verification result. */
        BackupFreshness: {
            /** @enum {string} */
            state: "current" | "not_recorded" | "stale" | "invalid" | "unavailable";
            /** Format: date-time */
            completedAt?: string | null;
            /** @enum {string} */
            driver?: "postgres" | "sqlite";
        };
        /** @description A redacted operational snapshot for an administrator. It never includes credentials, backup paths, prompt content, or raw provider errors. */
        AdminReadiness: {
            appVersion: string;
            commit?: string;
            /** @enum {string} */
            databaseDriver: "postgres" | "sqlite";
            migrationVersion: number;
            migrationDirty: boolean;
            backup: components["schemas"]["BackupFreshness"];
            upstreams: components["schemas"]["UpstreamHealth"][];
        };
        ChatSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: uuid
             * @description Optional user-owned project containing this chat.
             */
            projectId?: string;
            /**
             * Format: date-time
             * @description Present when the chat is archived.
             */
            archivedAt?: string;
            /**
             * Format: date-time
             * @description Present when the chat is pinned.
             */
            pinnedAt?: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateProjectRequest: {
            name: string;
        };
        RenameProjectRequest: {
            name: string;
        };
        ProjectAssignmentRequest: {
            /** Format: uuid */
            projectId: string;
        };
        MessageToolCall: {
            id: string;
            name: string;
            arguments: string;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "tool";
            /** @description The model that completed this turn. Omitted for messages created before model attribution was introduced. */
            model?: string;
            content: string;
            /** @description True when this is an interrupted turn checkpoint. It is visible on reload but is never replayed into a future model request. */
            incomplete?: boolean;
            thinking?: string;
            toolCalls?: components["schemas"]["MessageToolCall"][];
            toolCallId?: string;
            isError?: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        Chat: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @description The model id the chat was created with (used for continuation). */
            model: string;
            settings?: components["schemas"]["ChatSettings"];
        };
        /** @description A page of the caller's chats. total is a scoped, indexed count (by user_id) — cheap regardless of dataset size. */
        ChatList: {
            items: components["schemas"]["ChatSummary"][];
            limit: number;
            offset: number;
            total: number;
        };
        /** @description A page of one chat's messages, oldest-first. total is a scoped, indexed count (by chat_id) — cheap regardless of dataset size. */
        MessageList: {
            items: components["schemas"]["Message"][];
            limit: number;
            offset: number;
            total: number;
        };
        /** @description Per-chat model-generation settings. Every field is optional; an omitted field is unset — the provider default applies (temperature / topP / reasoningEffort / maxOutputTokens). maxHistoryTokens defaults to 100000 and caps the complete outbound prompt, including the sticky system message and current user message. */
        ChatSettings: {
            /** Format: double */
            temperature?: number;
            /** Format: double */
            topP?: number;
            /** @enum {string} */
            reasoningEffort?: "minimal" | "low" | "medium" | "high";
            maxOutputTokens?: number;
            maxHistoryTokens?: number;
        };
        PromptContextPreviewRequest: {
            /** @description The unsent user message to include in the preview. */
            message: string;
        };
        /** @description The exact context selection the next turn would use, counted by the server tokenizer. availableTokens is zero when sticky instructions and the current message alone exceed the configured history budget. */
        PromptContextPreview: {
            budgetTokens: number;
            systemTokens: number;
            historyTokens: number;
            currentMessageTokens: number;
            totalTokens: number;
            availableTokens: number;
            retainedMessages: number;
            retainedTurns: number;
            omittedMessages: number;
            omittedTurns: number;
        };
        /** @description An MCP server as it applies to a chat: the server's identity and live global connection status, plus whether it is enabled for THIS chat. Enablement here is per-chat and independent of the server's global enabled flag (see MCPServer.enabled) — a globally-disabled server is not available to any chat regardless. */
        ChatMCPServer: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * @description Live global connection status of the server.
             * @enum {string}
             */
            status: "connecting" | "connected" | "failed" | "disabled";
            /** @description Whether this server's tools are available to this chat. */
            enabled: boolean;
        };
        ChatMCPServerUpdate: {
            /** @description Enable or disable this server's tools for this chat. */
            enabled: boolean;
        };
        CreateChatRequest: {
            model: string;
            message: string;
        };
        ContinueChatRequest: {
            message: string;
            /** @description Model for this and subsequent turns; switching it updates the chat's model. Omit to keep the chat's current model. */
            model?: string;
        };
        MCPServer: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            transport: "stdio" | "http";
            command?: string;
            url?: string;
            enabled: boolean;
            /**
             * @description Live connection state of the server.
             * @enum {string}
             */
            status: "connecting" | "connected" | "failed" | "disabled";
            /** @description Error detail, present when status is failed. */
            statusError?: string;
            /**
             * @description Coarse failure classification, present when status is failed.
             * @enum {string}
             */
            statusReason?: "unreachable" | "access_denied" | "not_responding" | "failed";
            /** @description Number of tools discovered, present when connected. */
            toolCount?: number;
            /**
             * Format: date-time
             * @description UTC time at which the most recent connection attempt started.
             */
            lastConnectionAttemptAt?: string;
            /**
             * Format: date-time
             * @description UTC time at which this server most recently connected successfully.
             */
            lastSuccessfulConnectionAt?: string;
            /**
             * Format: date-time
             * @description UTC time at which this server most recently failed to connect or disconnected unexpectedly.
             */
            lastConnectionFailureAt?: string;
            /** @description Elapsed milliseconds for the most recent completed connection attempt. */
            lastConnectionLatencyMs?: number;
            /** @description Most recent connection or unexpected-disconnect error detail. Admin-only and never includes decrypted credentials. */
            lastError?: string;
            /** @description Command arguments (stdio transport). */
            args?: string[];
            /** @description HTTP headers (http transport). Authorization values are returned as '<scheme> [SECRET]' for edit prefill; resubmitting that unchanged value preserves the existing sealed credential. Other header values are returned as configured. Admin-only response; sealed at rest and never logged (the request logger records no bodies). */
            headers?: {
                [key: string]: string;
            };
            /** @description Environment variables (stdio transport), decrypted for edit prefill. Admin-only response; sealed at rest, never logged. */
            env?: {
                [key: string]: string;
            };
        };
        /** @description Edit an MCP server. Every field is optional; an omitted field keeps its current value. Providing transport-specific fields replaces them. */
        UpdateMCPServerRequest: {
            name?: string;
            /** @enum {string} */
            transport?: "stdio" | "http";
            command?: string;
            args?: string[];
            url?: string;
            /** @description HTTP headers to replace. An Authorization value returned as '<scheme> [SECRET]' preserves the existing sealed credential when sent back unchanged; any other value replaces it. */
            headers?: {
                [key: string]: string;
            };
            env?: {
                [key: string]: string;
            };
            enabled?: boolean;
        };
        RenameChatRequest: {
            title: string;
        };
        CreateMCPServerRequest: {
            name: string;
            /** @enum {string} */
            transport: "stdio" | "http";
            command?: string;
            args?: string[];
            url?: string;
            headers?: {
                [key: string]: string;
            };
            env?: {
                [key: string]: string;
            };
        };
        ImportMCPRequest: {
            /** @description Raw .mcp.json file content (Claude-style). */
            content: string;
        };
        MCPImportResult: {
            imported: components["schemas"]["MCPServer"][];
        };
        MCPTool: {
            /** @description Unqualified tool name (no server prefix). */
            name: string;
            description: string;
            /** @description The tool's input JSON Schema. */
            parameters: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Present only when single-user passwordless auto-login mints a fresh session for the sole admin on first load. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Admin created and logged in */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"][];
                };
            };
        };
    };
    listUpstreamHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamHealth"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAdminReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminReadiness"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listChats: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Select archived chats instead of active chats. */
                archived?: boolean;
                /** @description Case-insensitive literal title search. */
                search?: string;
                /** @description Limit the list to one caller-owned project. */
                projectId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatList"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    createChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatRequest"];
            };
        };
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getOrCreateEmptyChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"];
                };
            };
        };
    };
    getChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    continueChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContinueChatRequest"];
            };
        };
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    renameChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameChatRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listChatMessages: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateChatSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSettings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    previewChatContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptContextPreviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptContextPreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listChatMCPServers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMCPServer"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateChatMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
                serverId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMCPServerUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMCPServer"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    archiveChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    unarchiveChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    pinChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    unpinChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    assignChatProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectAssignmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    clearChatProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    renameProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listMCPServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPServer"][];
                };
            };
        };
    };
    createMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMCPServerRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPServer"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMCPServerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPServer"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    reconnectMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPServer"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listMCPServerTools: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPTool"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    importMCP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportMCPRequest"];
            };
        };
        responses: {
            /** @description Imported */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPImportResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
