// Package webassets embeds the built SvelteKit static SPA so the single Go
// binary serves both the API and the UI. The real build artifacts under dist/
// are generated by `make web-embed` (which syncs web/build/ into dist/) and are
// gitignored; only a placeholder dist/index.html is committed so `go build` and
// the test suite always compile even without a fresh SPA build.
package webassets

import (
	"bytes"
	"embed"
	"io/fs"

	"github.com/psyb0t/ctxerrors"
)

// placeholderMarker is a sentinel string present ONLY in the committed
// placeholder index.html. A real SvelteKit build never contains it, so its
// presence tells callers the SPA has not been built yet.
const placeholderMarker = "CHATZ_SPA_PLACEHOLDER"

//go:embed all:dist
var embedded embed.FS

// FS returns the embedded SPA rooted at dist/ (so "index.html" and "_app/..."
// resolve directly). It never returns nil on success — an empty tree still
// yields a usable fs.FS.
func FS() (fs.FS, error) {
	sub, err := fs.Sub(embedded, "dist")
	if err != nil {
		return nil, ctxerrors.Wrap(err, "sub embedded dist")
	}

	return sub, nil
}

// IsPlaceholder reports whether the embedded SPA is only the committed
// placeholder (i.e. `make web-embed` was never run). Callers can warn on boot
// so a placeholder UI is never mistaken for a real one.
func IsPlaceholder(fsys fs.FS) bool {
	data, err := fs.ReadFile(fsys, "index.html")
	if err != nil {
		return true
	}

	return bytes.Contains(data, []byte(placeholderMarker))
}
