// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/chatz/internal/pkg/db/models"

	"github.com/google/uuid"
)

func newChat(db *gorm.DB, opts ...gen.DOOption) chat {
	_chat := chat{}

	_chat.chatDo.UseDB(db, opts...)
	_chat.chatDo.UseModel(&models.Chat{})

	tableName := _chat.chatDo.TableName()
	_chat.ALL = field.NewAsterisk(tableName)
	_chat.ID = field.NewField(tableName, "id")
	_chat.CreatedAt = field.NewTime(tableName, "created_at")
	_chat.UpdatedAt = field.NewTime(tableName, "updated_at")
	_chat.DeletedAt = field.NewField(tableName, "deleted_at")
	_chat.UserID = field.NewField(tableName, "user_id")
	_chat.Title = field.NewString(tableName, "title")
	_chat.ModelID = field.NewString(tableName, "model_id")
	_chat.ProjectID = field.NewField(tableName, "project_id")
	_chat.ArchivedAt = field.NewTime(tableName, "archived_at")
	_chat.PinnedAt = field.NewTime(tableName, "pinned_at")
	_chat.Temperature = field.NewFloat64(tableName, "temperature")
	_chat.TopP = field.NewFloat64(tableName, "top_p")
	_chat.ReasoningEffort = field.NewString(tableName, "reasoning_effort")
	_chat.MaxOutputTokens = field.NewInt(tableName, "max_output_tokens")
	_chat.MaxHistoryTokens = field.NewInt(tableName, "max_history_tokens")
	_chat.DisabledMCPServerIDs = field.NewField(tableName, "disabled_mcp_server_ids")

	_chat.fillFieldMap()

	return _chat
}

type chat struct {
	chatDo

	ALL                  field.Asterisk
	ID                   field.Field
	CreatedAt            field.Time
	UpdatedAt            field.Time
	DeletedAt            field.Field
	UserID               field.Field
	Title                field.String
	ModelID              field.String
	ProjectID            field.Field
	ArchivedAt           field.Time
	PinnedAt             field.Time
	Temperature          field.Float64
	TopP                 field.Float64
	ReasoningEffort      field.String
	MaxOutputTokens      field.Int
	MaxHistoryTokens     field.Int
	DisabledMCPServerIDs field.Field

	fieldMap map[string]field.Expr
}

func (c chat) Table(newTableName string) *chat {
	c.chatDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chat) As(alias string) *chat {
	c.chatDo.DO = *(c.chatDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chat) updateTableName(table string) *chat {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewField(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.UserID = field.NewField(table, "user_id")
	c.Title = field.NewString(table, "title")
	c.ModelID = field.NewString(table, "model_id")
	c.ProjectID = field.NewField(table, "project_id")
	c.ArchivedAt = field.NewTime(table, "archived_at")
	c.PinnedAt = field.NewTime(table, "pinned_at")
	c.Temperature = field.NewFloat64(table, "temperature")
	c.TopP = field.NewFloat64(table, "top_p")
	c.ReasoningEffort = field.NewString(table, "reasoning_effort")
	c.MaxOutputTokens = field.NewInt(table, "max_output_tokens")
	c.MaxHistoryTokens = field.NewInt(table, "max_history_tokens")
	c.DisabledMCPServerIDs = field.NewField(table, "disabled_mcp_server_ids")

	c.fillFieldMap()

	return c
}

func (c *chat) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chat) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 16)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["title"] = c.Title
	c.fieldMap["model_id"] = c.ModelID
	c.fieldMap["project_id"] = c.ProjectID
	c.fieldMap["archived_at"] = c.ArchivedAt
	c.fieldMap["pinned_at"] = c.PinnedAt
	c.fieldMap["temperature"] = c.Temperature
	c.fieldMap["top_p"] = c.TopP
	c.fieldMap["reasoning_effort"] = c.ReasoningEffort
	c.fieldMap["max_output_tokens"] = c.MaxOutputTokens
	c.fieldMap["max_history_tokens"] = c.MaxHistoryTokens
	c.fieldMap["disabled_mcp_server_ids"] = c.DisabledMCPServerIDs
}

func (c chat) clone(db *gorm.DB) chat {
	c.chatDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chat) replaceDB(db *gorm.DB) chat {
	c.chatDo.ReplaceDB(db)
	return c
}

type chatDo struct{ gen.DO }

type IChatDo interface {
	gen.SubQuery
	Debug() IChatDo
	WithContext(ctx context.Context) IChatDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChatDo
	WriteDB() IChatDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChatDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChatDo
	Not(conds ...gen.Condition) IChatDo
	Or(conds ...gen.Condition) IChatDo
	Select(conds ...field.Expr) IChatDo
	Where(conds ...gen.Condition) IChatDo
	Order(conds ...field.Expr) IChatDo
	Distinct(cols ...field.Expr) IChatDo
	Omit(cols ...field.Expr) IChatDo
	Join(table schema.Tabler, on ...field.Expr) IChatDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChatDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChatDo
	Group(cols ...field.Expr) IChatDo
	Having(conds ...gen.Condition) IChatDo
	Limit(limit int) IChatDo
	Offset(offset int) IChatDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChatDo
	Unscoped() IChatDo
	Create(values ...*models.Chat) error
	CreateInBatches(values []*models.Chat, batchSize int) error
	Save(values ...*models.Chat) error
	First() (*models.Chat, error)
	Take() (*models.Chat, error)
	Last() (*models.Chat, error)
	Find() ([]*models.Chat, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Chat, err error)
	FindInBatches(result *[]*models.Chat, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Chat) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChatDo
	Assign(attrs ...field.AssignExpr) IChatDo
	Joins(fields ...field.RelationField) IChatDo
	Preload(fields ...field.RelationField) IChatDo
	FirstOrInit() (*models.Chat, error)
	FirstOrCreate() (*models.Chat, error)
	FindByPage(offset int, limit int) (result []*models.Chat, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChatDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	FindEmptyChat(userID uuid.UUID) (result []*models.Chat, err error)
	ListNonEmpty(userID uuid.UUID, archived bool, search string, projectID *uuid.UUID, limit int, offset int) (result []*models.Chat, err error)
	CountNonEmpty(userID uuid.UUID, archived bool, search string, projectID *uuid.UUID) (result int64, err error)
}

// FindEmptyChat returns the caller's oldest chat with zero user messages,
// at most one row. An empty result slice means the user currently
// has no empty chat.
//
// SELECT c.*
// FROM chats c
// WHERE c.user_id = @userID
// AND c.deleted_at IS NULL
// AND NOT EXISTS (
//
//	SELECT 1 FROM messages m
//	WHERE m.chat_id = c.id AND m.role = 'user'
//
// )
// ORDER BY c.created_at ASC
// LIMIT 1
func (c chatDo) FindEmptyChat(userID uuid.UUID) (result []*models.Chat, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	generateSQL.WriteString("SELECT c.* FROM chats c WHERE c.user_id = ? AND c.deleted_at IS NULL AND NOT EXISTS ( SELECT 1 FROM messages m WHERE m.chat_id = c.id AND m.role = 'user' ) ORDER BY c.created_at ASC LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListNonEmpty returns a filtered page of the user's chats that have at
// least one user message. Pinned chats sort first, then newest activity.
//
//	SELECT c.*
//	FROM chats c
//	WHERE c.user_id = @userID
//	  AND c.deleted_at IS NULL
//	  {{if archived}}
//	  AND c.archived_at IS NOT NULL
//	  {{else}}
//	  AND c.archived_at IS NULL
//	  {{end}}
//	  {{if search != ""}}
//	  AND LOWER(c.title) LIKE LOWER(@search) ESCAPE '!'
//	  {{end}}
//	  {{if projectID != nil}} AND c.project_id = @projectID {{end}}
//	  AND EXISTS (
//	      SELECT 1 FROM messages m
//	      WHERE m.chat_id = c.id AND m.role = 'user'
//	  )
//	ORDER BY CASE WHEN c.pinned_at IS NULL THEN 1 ELSE 0 END,
//	         c.pinned_at DESC,
//	         c.updated_at DESC
//	{{if limit > 0}} LIMIT @limit {{end}}
//	{{if offset > 0}} OFFSET @offset {{end}}
func (c chatDo) ListNonEmpty(userID uuid.UUID, archived bool, search string, projectID *uuid.UUID, limit int, offset int) (result []*models.Chat, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	generateSQL.WriteString("SELECT c.* FROM chats c WHERE c.user_id = ? AND c.deleted_at IS NULL ")
	if archived {
		generateSQL.WriteString("AND c.archived_at IS NOT NULL ")
	} else {
		generateSQL.WriteString("AND c.archived_at IS NULL ")
	}
	if search != "" {
		params = append(params, search)
		generateSQL.WriteString("AND LOWER(c.title) LIKE LOWER(?) ESCAPE '!' ")
	}
	if projectID != nil {
		params = append(params, projectID)
		generateSQL.WriteString("AND c.project_id = ? ")
	}
	generateSQL.WriteString("AND EXISTS ( SELECT 1 FROM messages m WHERE m.chat_id = c.id AND m.role = 'user' ) ORDER BY CASE WHEN c.pinned_at IS NULL THEN 1 ELSE 0 END, c.pinned_at DESC, c.updated_at DESC ")
	if limit > 0 {
		params = append(params, limit)
		generateSQL.WriteString("LIMIT ? ")
	}
	if offset > 0 {
		params = append(params, offset)
		generateSQL.WriteString("OFFSET ? ")
	}

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// CountNonEmpty returns the total count matching ListNonEmpty's filter,
// for the list endpoint's pagination envelope.
//
//	SELECT COUNT(*)
//	FROM chats c
//	WHERE c.user_id = @userID
//	  AND c.deleted_at IS NULL
//	  {{if archived}}
//	  AND c.archived_at IS NOT NULL
//	  {{else}}
//	  AND c.archived_at IS NULL
//	  {{end}}
//	  {{if search != ""}}
//	  AND LOWER(c.title) LIKE LOWER(@search) ESCAPE '!'
//	  {{end}}
//	  {{if projectID != nil}} AND c.project_id = @projectID {{end}}
//	  AND EXISTS (
//	      SELECT 1 FROM messages m
//	      WHERE m.chat_id = c.id AND m.role = 'user'
//	  )
func (c chatDo) CountNonEmpty(userID uuid.UUID, archived bool, search string, projectID *uuid.UUID) (result int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	generateSQL.WriteString("SELECT COUNT(*) FROM chats c WHERE c.user_id = ? AND c.deleted_at IS NULL ")
	if archived {
		generateSQL.WriteString("AND c.archived_at IS NOT NULL ")
	} else {
		generateSQL.WriteString("AND c.archived_at IS NULL ")
	}
	if search != "" {
		params = append(params, search)
		generateSQL.WriteString("AND LOWER(c.title) LIKE LOWER(?) ESCAPE '!' ")
	}
	if projectID != nil {
		params = append(params, projectID)
		generateSQL.WriteString("AND c.project_id = ? ")
	}
	generateSQL.WriteString("AND EXISTS ( SELECT 1 FROM messages m WHERE m.chat_id = c.id AND m.role = 'user' ) ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (c chatDo) Debug() IChatDo {
	return c.withDO(c.DO.Debug())
}

func (c chatDo) WithContext(ctx context.Context) IChatDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chatDo) ReadDB() IChatDo {
	return c.Clauses(dbresolver.Read)
}

func (c chatDo) WriteDB() IChatDo {
	return c.Clauses(dbresolver.Write)
}

func (c chatDo) Session(config *gorm.Session) IChatDo {
	return c.withDO(c.DO.Session(config))
}

func (c chatDo) Clauses(conds ...clause.Expression) IChatDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chatDo) Returning(value interface{}, columns ...string) IChatDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chatDo) Not(conds ...gen.Condition) IChatDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chatDo) Or(conds ...gen.Condition) IChatDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chatDo) Select(conds ...field.Expr) IChatDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chatDo) Where(conds ...gen.Condition) IChatDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chatDo) Order(conds ...field.Expr) IChatDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chatDo) Distinct(cols ...field.Expr) IChatDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chatDo) Omit(cols ...field.Expr) IChatDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chatDo) Join(table schema.Tabler, on ...field.Expr) IChatDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chatDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChatDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chatDo) RightJoin(table schema.Tabler, on ...field.Expr) IChatDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chatDo) Group(cols ...field.Expr) IChatDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chatDo) Having(conds ...gen.Condition) IChatDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chatDo) Limit(limit int) IChatDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chatDo) Offset(offset int) IChatDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chatDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChatDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chatDo) Unscoped() IChatDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chatDo) Create(values ...*models.Chat) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chatDo) CreateInBatches(values []*models.Chat, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chatDo) Save(values ...*models.Chat) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chatDo) First() (*models.Chat, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Chat), nil
	}
}

func (c chatDo) Take() (*models.Chat, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Chat), nil
	}
}

func (c chatDo) Last() (*models.Chat, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Chat), nil
	}
}

func (c chatDo) Find() ([]*models.Chat, error) {
	result, err := c.DO.Find()
	return result.([]*models.Chat), err
}

func (c chatDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Chat, err error) {
	buf := make([]*models.Chat, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chatDo) FindInBatches(result *[]*models.Chat, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chatDo) Attrs(attrs ...field.AssignExpr) IChatDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chatDo) Assign(attrs ...field.AssignExpr) IChatDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chatDo) Joins(fields ...field.RelationField) IChatDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chatDo) Preload(fields ...field.RelationField) IChatDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chatDo) FirstOrInit() (*models.Chat, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Chat), nil
	}
}

func (c chatDo) FirstOrCreate() (*models.Chat, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Chat), nil
	}
}

func (c chatDo) FindByPage(offset int, limit int) (result []*models.Chat, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chatDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chatDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chatDo) Delete(models ...*models.Chat) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chatDo) withDO(do gen.Dao) *chatDo {
	c.DO = *do.(*gen.DO)
	return c
}
