// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/chatz/internal/pkg/db/models"
)

func newLLMUsage(db *gorm.DB, opts ...gen.DOOption) lLMUsage {
	_lLMUsage := lLMUsage{}

	_lLMUsage.lLMUsageDo.UseDB(db, opts...)
	_lLMUsage.lLMUsageDo.UseModel(&models.LLMUsage{})

	tableName := _lLMUsage.lLMUsageDo.TableName()
	_lLMUsage.ALL = field.NewAsterisk(tableName)
	_lLMUsage.ID = field.NewField(tableName, "id")
	_lLMUsage.CreatedAt = field.NewTime(tableName, "created_at")
	_lLMUsage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_lLMUsage.DeletedAt = field.NewField(tableName, "deleted_at")
	_lLMUsage.Service = field.NewString(tableName, "service")
	_lLMUsage.Stage = field.NewString(tableName, "stage")
	_lLMUsage.Model = field.NewString(tableName, "model")
	_lLMUsage.ReasoningEffort = field.NewString(tableName, "reasoning_effort")
	_lLMUsage.PromptTokens = field.NewInt64(tableName, "prompt_tokens")
	_lLMUsage.CachedPromptTokens = field.NewInt64(tableName, "cached_prompt_tokens")
	_lLMUsage.CompletionTokens = field.NewInt64(tableName, "completion_tokens")
	_lLMUsage.ReasoningTokens = field.NewInt64(tableName, "reasoning_tokens")
	_lLMUsage.TotalTokens = field.NewInt64(tableName, "total_tokens")
	_lLMUsage.DurationMs = field.NewInt64(tableName, "duration_ms")
	_lLMUsage.UserID = field.NewField(tableName, "user_id")
	_lLMUsage.ChatID = field.NewField(tableName, "chat_id")
	_lLMUsage.MessageID = field.NewField(tableName, "message_id")
	_lLMUsage.RequestID = field.NewString(tableName, "request_id")
	_lLMUsage.ErrorMessage = field.NewString(tableName, "error_message")

	_lLMUsage.fillFieldMap()

	return _lLMUsage
}

type lLMUsage struct {
	lLMUsageDo

	ALL                field.Asterisk
	ID                 field.Field
	CreatedAt          field.Time
	UpdatedAt          field.Time
	DeletedAt          field.Field
	Service            field.String
	Stage              field.String
	Model              field.String
	ReasoningEffort    field.String
	PromptTokens       field.Int64
	CachedPromptTokens field.Int64
	CompletionTokens   field.Int64
	ReasoningTokens    field.Int64
	TotalTokens        field.Int64
	DurationMs         field.Int64
	UserID             field.Field
	ChatID             field.Field
	MessageID          field.Field
	RequestID          field.String
	ErrorMessage       field.String

	fieldMap map[string]field.Expr
}

func (l lLMUsage) Table(newTableName string) *lLMUsage {
	l.lLMUsageDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lLMUsage) As(alias string) *lLMUsage {
	l.lLMUsageDo.DO = *(l.lLMUsageDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lLMUsage) updateTableName(table string) *lLMUsage {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewField(table, "id")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")
	l.DeletedAt = field.NewField(table, "deleted_at")
	l.Service = field.NewString(table, "service")
	l.Stage = field.NewString(table, "stage")
	l.Model = field.NewString(table, "model")
	l.ReasoningEffort = field.NewString(table, "reasoning_effort")
	l.PromptTokens = field.NewInt64(table, "prompt_tokens")
	l.CachedPromptTokens = field.NewInt64(table, "cached_prompt_tokens")
	l.CompletionTokens = field.NewInt64(table, "completion_tokens")
	l.ReasoningTokens = field.NewInt64(table, "reasoning_tokens")
	l.TotalTokens = field.NewInt64(table, "total_tokens")
	l.DurationMs = field.NewInt64(table, "duration_ms")
	l.UserID = field.NewField(table, "user_id")
	l.ChatID = field.NewField(table, "chat_id")
	l.MessageID = field.NewField(table, "message_id")
	l.RequestID = field.NewString(table, "request_id")
	l.ErrorMessage = field.NewString(table, "error_message")

	l.fillFieldMap()

	return l
}

func (l *lLMUsage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lLMUsage) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 19)
	l.fieldMap["id"] = l.ID
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
	l.fieldMap["deleted_at"] = l.DeletedAt
	l.fieldMap["service"] = l.Service
	l.fieldMap["stage"] = l.Stage
	l.fieldMap["model"] = l.Model
	l.fieldMap["reasoning_effort"] = l.ReasoningEffort
	l.fieldMap["prompt_tokens"] = l.PromptTokens
	l.fieldMap["cached_prompt_tokens"] = l.CachedPromptTokens
	l.fieldMap["completion_tokens"] = l.CompletionTokens
	l.fieldMap["reasoning_tokens"] = l.ReasoningTokens
	l.fieldMap["total_tokens"] = l.TotalTokens
	l.fieldMap["duration_ms"] = l.DurationMs
	l.fieldMap["user_id"] = l.UserID
	l.fieldMap["chat_id"] = l.ChatID
	l.fieldMap["message_id"] = l.MessageID
	l.fieldMap["request_id"] = l.RequestID
	l.fieldMap["error_message"] = l.ErrorMessage
}

func (l lLMUsage) clone(db *gorm.DB) lLMUsage {
	l.lLMUsageDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lLMUsage) replaceDB(db *gorm.DB) lLMUsage {
	l.lLMUsageDo.ReplaceDB(db)
	return l
}

type lLMUsageDo struct{ gen.DO }

type ILLMUsageDo interface {
	gen.SubQuery
	Debug() ILLMUsageDo
	WithContext(ctx context.Context) ILLMUsageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILLMUsageDo
	WriteDB() ILLMUsageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILLMUsageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILLMUsageDo
	Not(conds ...gen.Condition) ILLMUsageDo
	Or(conds ...gen.Condition) ILLMUsageDo
	Select(conds ...field.Expr) ILLMUsageDo
	Where(conds ...gen.Condition) ILLMUsageDo
	Order(conds ...field.Expr) ILLMUsageDo
	Distinct(cols ...field.Expr) ILLMUsageDo
	Omit(cols ...field.Expr) ILLMUsageDo
	Join(table schema.Tabler, on ...field.Expr) ILLMUsageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILLMUsageDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILLMUsageDo
	Group(cols ...field.Expr) ILLMUsageDo
	Having(conds ...gen.Condition) ILLMUsageDo
	Limit(limit int) ILLMUsageDo
	Offset(offset int) ILLMUsageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILLMUsageDo
	Unscoped() ILLMUsageDo
	Create(values ...*models.LLMUsage) error
	CreateInBatches(values []*models.LLMUsage, batchSize int) error
	Save(values ...*models.LLMUsage) error
	First() (*models.LLMUsage, error)
	Take() (*models.LLMUsage, error)
	Last() (*models.LLMUsage, error)
	Find() ([]*models.LLMUsage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LLMUsage, err error)
	FindInBatches(result *[]*models.LLMUsage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.LLMUsage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILLMUsageDo
	Assign(attrs ...field.AssignExpr) ILLMUsageDo
	Joins(fields ...field.RelationField) ILLMUsageDo
	Preload(fields ...field.RelationField) ILLMUsageDo
	FirstOrInit() (*models.LLMUsage, error)
	FirstOrCreate() (*models.LLMUsage, error)
	FindByPage(offset int, limit int) (result []*models.LLMUsage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILLMUsageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l lLMUsageDo) Debug() ILLMUsageDo {
	return l.withDO(l.DO.Debug())
}

func (l lLMUsageDo) WithContext(ctx context.Context) ILLMUsageDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lLMUsageDo) ReadDB() ILLMUsageDo {
	return l.Clauses(dbresolver.Read)
}

func (l lLMUsageDo) WriteDB() ILLMUsageDo {
	return l.Clauses(dbresolver.Write)
}

func (l lLMUsageDo) Session(config *gorm.Session) ILLMUsageDo {
	return l.withDO(l.DO.Session(config))
}

func (l lLMUsageDo) Clauses(conds ...clause.Expression) ILLMUsageDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lLMUsageDo) Returning(value interface{}, columns ...string) ILLMUsageDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lLMUsageDo) Not(conds ...gen.Condition) ILLMUsageDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lLMUsageDo) Or(conds ...gen.Condition) ILLMUsageDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lLMUsageDo) Select(conds ...field.Expr) ILLMUsageDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lLMUsageDo) Where(conds ...gen.Condition) ILLMUsageDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lLMUsageDo) Order(conds ...field.Expr) ILLMUsageDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lLMUsageDo) Distinct(cols ...field.Expr) ILLMUsageDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lLMUsageDo) Omit(cols ...field.Expr) ILLMUsageDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lLMUsageDo) Join(table schema.Tabler, on ...field.Expr) ILLMUsageDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lLMUsageDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILLMUsageDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lLMUsageDo) RightJoin(table schema.Tabler, on ...field.Expr) ILLMUsageDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lLMUsageDo) Group(cols ...field.Expr) ILLMUsageDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lLMUsageDo) Having(conds ...gen.Condition) ILLMUsageDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lLMUsageDo) Limit(limit int) ILLMUsageDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lLMUsageDo) Offset(offset int) ILLMUsageDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lLMUsageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILLMUsageDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lLMUsageDo) Unscoped() ILLMUsageDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lLMUsageDo) Create(values ...*models.LLMUsage) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lLMUsageDo) CreateInBatches(values []*models.LLMUsage, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lLMUsageDo) Save(values ...*models.LLMUsage) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lLMUsageDo) First() (*models.LLMUsage, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMUsage), nil
	}
}

func (l lLMUsageDo) Take() (*models.LLMUsage, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMUsage), nil
	}
}

func (l lLMUsageDo) Last() (*models.LLMUsage, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMUsage), nil
	}
}

func (l lLMUsageDo) Find() ([]*models.LLMUsage, error) {
	result, err := l.DO.Find()
	return result.([]*models.LLMUsage), err
}

func (l lLMUsageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LLMUsage, err error) {
	buf := make([]*models.LLMUsage, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lLMUsageDo) FindInBatches(result *[]*models.LLMUsage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lLMUsageDo) Attrs(attrs ...field.AssignExpr) ILLMUsageDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lLMUsageDo) Assign(attrs ...field.AssignExpr) ILLMUsageDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lLMUsageDo) Joins(fields ...field.RelationField) ILLMUsageDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lLMUsageDo) Preload(fields ...field.RelationField) ILLMUsageDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lLMUsageDo) FirstOrInit() (*models.LLMUsage, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMUsage), nil
	}
}

func (l lLMUsageDo) FirstOrCreate() (*models.LLMUsage, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMUsage), nil
	}
}

func (l lLMUsageDo) FindByPage(offset int, limit int) (result []*models.LLMUsage, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lLMUsageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lLMUsageDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lLMUsageDo) Delete(models ...*models.LLMUsage) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lLMUsageDo) withDO(do gen.Dao) *lLMUsageDo {
	l.DO = *do.(*gen.DO)
	return l
}
