// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/chatz/internal/pkg/db/models"
)

func newMCPToolExecution(db *gorm.DB, opts ...gen.DOOption) mCPToolExecution {
	_mCPToolExecution := mCPToolExecution{}

	_mCPToolExecution.mCPToolExecutionDo.UseDB(db, opts...)
	_mCPToolExecution.mCPToolExecutionDo.UseModel(&models.MCPToolExecution{})

	tableName := _mCPToolExecution.mCPToolExecutionDo.TableName()
	_mCPToolExecution.ALL = field.NewAsterisk(tableName)
	_mCPToolExecution.ID = field.NewField(tableName, "id")
	_mCPToolExecution.CreatedAt = field.NewTime(tableName, "created_at")
	_mCPToolExecution.UpdatedAt = field.NewTime(tableName, "updated_at")
	_mCPToolExecution.DeletedAt = field.NewField(tableName, "deleted_at")
	_mCPToolExecution.MessageID = field.NewField(tableName, "message_id")
	_mCPToolExecution.Server = field.NewString(tableName, "server")
	_mCPToolExecution.Tool = field.NewString(tableName, "tool")
	_mCPToolExecution.Params = field.NewField(tableName, "params")
	_mCPToolExecution.Result = field.NewString(tableName, "result")
	_mCPToolExecution.IsError = field.NewBool(tableName, "is_error")
	_mCPToolExecution.DurationMs = field.NewInt64(tableName, "duration_ms")

	_mCPToolExecution.fillFieldMap()

	return _mCPToolExecution
}

type mCPToolExecution struct {
	mCPToolExecutionDo

	ALL        field.Asterisk
	ID         field.Field
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field
	MessageID  field.Field
	Server     field.String
	Tool       field.String
	Params     field.Field
	Result     field.String
	IsError    field.Bool
	DurationMs field.Int64

	fieldMap map[string]field.Expr
}

func (m mCPToolExecution) Table(newTableName string) *mCPToolExecution {
	m.mCPToolExecutionDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mCPToolExecution) As(alias string) *mCPToolExecution {
	m.mCPToolExecutionDo.DO = *(m.mCPToolExecutionDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mCPToolExecution) updateTableName(table string) *mCPToolExecution {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewField(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.MessageID = field.NewField(table, "message_id")
	m.Server = field.NewString(table, "server")
	m.Tool = field.NewString(table, "tool")
	m.Params = field.NewField(table, "params")
	m.Result = field.NewString(table, "result")
	m.IsError = field.NewBool(table, "is_error")
	m.DurationMs = field.NewInt64(table, "duration_ms")

	m.fillFieldMap()

	return m
}

func (m *mCPToolExecution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mCPToolExecution) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 11)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["message_id"] = m.MessageID
	m.fieldMap["server"] = m.Server
	m.fieldMap["tool"] = m.Tool
	m.fieldMap["params"] = m.Params
	m.fieldMap["result"] = m.Result
	m.fieldMap["is_error"] = m.IsError
	m.fieldMap["duration_ms"] = m.DurationMs
}

func (m mCPToolExecution) clone(db *gorm.DB) mCPToolExecution {
	m.mCPToolExecutionDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mCPToolExecution) replaceDB(db *gorm.DB) mCPToolExecution {
	m.mCPToolExecutionDo.ReplaceDB(db)
	return m
}

type mCPToolExecutionDo struct{ gen.DO }

type IMCPToolExecutionDo interface {
	gen.SubQuery
	Debug() IMCPToolExecutionDo
	WithContext(ctx context.Context) IMCPToolExecutionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMCPToolExecutionDo
	WriteDB() IMCPToolExecutionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMCPToolExecutionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMCPToolExecutionDo
	Not(conds ...gen.Condition) IMCPToolExecutionDo
	Or(conds ...gen.Condition) IMCPToolExecutionDo
	Select(conds ...field.Expr) IMCPToolExecutionDo
	Where(conds ...gen.Condition) IMCPToolExecutionDo
	Order(conds ...field.Expr) IMCPToolExecutionDo
	Distinct(cols ...field.Expr) IMCPToolExecutionDo
	Omit(cols ...field.Expr) IMCPToolExecutionDo
	Join(table schema.Tabler, on ...field.Expr) IMCPToolExecutionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMCPToolExecutionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMCPToolExecutionDo
	Group(cols ...field.Expr) IMCPToolExecutionDo
	Having(conds ...gen.Condition) IMCPToolExecutionDo
	Limit(limit int) IMCPToolExecutionDo
	Offset(offset int) IMCPToolExecutionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMCPToolExecutionDo
	Unscoped() IMCPToolExecutionDo
	Create(values ...*models.MCPToolExecution) error
	CreateInBatches(values []*models.MCPToolExecution, batchSize int) error
	Save(values ...*models.MCPToolExecution) error
	First() (*models.MCPToolExecution, error)
	Take() (*models.MCPToolExecution, error)
	Last() (*models.MCPToolExecution, error)
	Find() ([]*models.MCPToolExecution, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MCPToolExecution, err error)
	FindInBatches(result *[]*models.MCPToolExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MCPToolExecution) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMCPToolExecutionDo
	Assign(attrs ...field.AssignExpr) IMCPToolExecutionDo
	Joins(fields ...field.RelationField) IMCPToolExecutionDo
	Preload(fields ...field.RelationField) IMCPToolExecutionDo
	FirstOrInit() (*models.MCPToolExecution, error)
	FirstOrCreate() (*models.MCPToolExecution, error)
	FindByPage(offset int, limit int) (result []*models.MCPToolExecution, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMCPToolExecutionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mCPToolExecutionDo) Debug() IMCPToolExecutionDo {
	return m.withDO(m.DO.Debug())
}

func (m mCPToolExecutionDo) WithContext(ctx context.Context) IMCPToolExecutionDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mCPToolExecutionDo) ReadDB() IMCPToolExecutionDo {
	return m.Clauses(dbresolver.Read)
}

func (m mCPToolExecutionDo) WriteDB() IMCPToolExecutionDo {
	return m.Clauses(dbresolver.Write)
}

func (m mCPToolExecutionDo) Session(config *gorm.Session) IMCPToolExecutionDo {
	return m.withDO(m.DO.Session(config))
}

func (m mCPToolExecutionDo) Clauses(conds ...clause.Expression) IMCPToolExecutionDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mCPToolExecutionDo) Returning(value interface{}, columns ...string) IMCPToolExecutionDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mCPToolExecutionDo) Not(conds ...gen.Condition) IMCPToolExecutionDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mCPToolExecutionDo) Or(conds ...gen.Condition) IMCPToolExecutionDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mCPToolExecutionDo) Select(conds ...field.Expr) IMCPToolExecutionDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mCPToolExecutionDo) Where(conds ...gen.Condition) IMCPToolExecutionDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mCPToolExecutionDo) Order(conds ...field.Expr) IMCPToolExecutionDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mCPToolExecutionDo) Distinct(cols ...field.Expr) IMCPToolExecutionDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mCPToolExecutionDo) Omit(cols ...field.Expr) IMCPToolExecutionDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mCPToolExecutionDo) Join(table schema.Tabler, on ...field.Expr) IMCPToolExecutionDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mCPToolExecutionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMCPToolExecutionDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mCPToolExecutionDo) RightJoin(table schema.Tabler, on ...field.Expr) IMCPToolExecutionDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mCPToolExecutionDo) Group(cols ...field.Expr) IMCPToolExecutionDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mCPToolExecutionDo) Having(conds ...gen.Condition) IMCPToolExecutionDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mCPToolExecutionDo) Limit(limit int) IMCPToolExecutionDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mCPToolExecutionDo) Offset(offset int) IMCPToolExecutionDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mCPToolExecutionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMCPToolExecutionDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mCPToolExecutionDo) Unscoped() IMCPToolExecutionDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mCPToolExecutionDo) Create(values ...*models.MCPToolExecution) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mCPToolExecutionDo) CreateInBatches(values []*models.MCPToolExecution, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mCPToolExecutionDo) Save(values ...*models.MCPToolExecution) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mCPToolExecutionDo) First() (*models.MCPToolExecution, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MCPToolExecution), nil
	}
}

func (m mCPToolExecutionDo) Take() (*models.MCPToolExecution, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MCPToolExecution), nil
	}
}

func (m mCPToolExecutionDo) Last() (*models.MCPToolExecution, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MCPToolExecution), nil
	}
}

func (m mCPToolExecutionDo) Find() ([]*models.MCPToolExecution, error) {
	result, err := m.DO.Find()
	return result.([]*models.MCPToolExecution), err
}

func (m mCPToolExecutionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MCPToolExecution, err error) {
	buf := make([]*models.MCPToolExecution, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mCPToolExecutionDo) FindInBatches(result *[]*models.MCPToolExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mCPToolExecutionDo) Attrs(attrs ...field.AssignExpr) IMCPToolExecutionDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mCPToolExecutionDo) Assign(attrs ...field.AssignExpr) IMCPToolExecutionDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mCPToolExecutionDo) Joins(fields ...field.RelationField) IMCPToolExecutionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mCPToolExecutionDo) Preload(fields ...field.RelationField) IMCPToolExecutionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mCPToolExecutionDo) FirstOrInit() (*models.MCPToolExecution, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MCPToolExecution), nil
	}
}

func (m mCPToolExecutionDo) FirstOrCreate() (*models.MCPToolExecution, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MCPToolExecution), nil
	}
}

func (m mCPToolExecutionDo) FindByPage(offset int, limit int) (result []*models.MCPToolExecution, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mCPToolExecutionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mCPToolExecutionDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mCPToolExecutionDo) Delete(models ...*models.MCPToolExecution) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mCPToolExecutionDo) withDO(do gen.Dao) *mCPToolExecutionDo {
	m.DO = *do.(*gen.DO)
	return m
}
