// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	Chat             *chat
	LLMUsage         *lLMUsage
	MCPServer        *mCPServer
	MCPToolExecution *mCPToolExecution
	Message          *message
	Project          *project
	Session          *session
	User             *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Chat = &Q.Chat
	LLMUsage = &Q.LLMUsage
	MCPServer = &Q.MCPServer
	MCPToolExecution = &Q.MCPToolExecution
	Message = &Q.Message
	Project = &Q.Project
	Session = &Q.Session
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		Chat:             newChat(db, opts...),
		LLMUsage:         newLLMUsage(db, opts...),
		MCPServer:        newMCPServer(db, opts...),
		MCPToolExecution: newMCPToolExecution(db, opts...),
		Message:          newMessage(db, opts...),
		Project:          newProject(db, opts...),
		Session:          newSession(db, opts...),
		User:             newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Chat             chat
	LLMUsage         lLMUsage
	MCPServer        mCPServer
	MCPToolExecution mCPToolExecution
	Message          message
	Project          project
	Session          session
	User             user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Chat:             q.Chat.clone(db),
		LLMUsage:         q.LLMUsage.clone(db),
		MCPServer:        q.MCPServer.clone(db),
		MCPToolExecution: q.MCPToolExecution.clone(db),
		Message:          q.Message.clone(db),
		Project:          q.Project.clone(db),
		Session:          q.Session.clone(db),
		User:             q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Chat:             q.Chat.replaceDB(db),
		LLMUsage:         q.LLMUsage.replaceDB(db),
		MCPServer:        q.MCPServer.replaceDB(db),
		MCPToolExecution: q.MCPToolExecution.replaceDB(db),
		Message:          q.Message.replaceDB(db),
		Project:          q.Project.replaceDB(db),
		Session:          q.Session.replaceDB(db),
		User:             q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Chat             IChatDo
	LLMUsage         ILLMUsageDo
	MCPServer        IMCPServerDo
	MCPToolExecution IMCPToolExecutionDo
	Message          IMessageDo
	Project          IProjectDo
	Session          ISessionDo
	User             IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Chat:             q.Chat.WithContext(ctx),
		LLMUsage:         q.LLMUsage.WithContext(ctx),
		MCPServer:        q.MCPServer.WithContext(ctx),
		MCPToolExecution: q.MCPToolExecution.WithContext(ctx),
		Message:          q.Message.WithContext(ctx),
		Project:          q.Project.WithContext(ctx),
		Session:          q.Session.WithContext(ctx),
		User:             q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
